### PR TITLE
adds Detroit

### PR DESCRIPTION
**Pull request by seafoam6**
Buddy's is the best

### CODE REVIEW

**Comment by mikedao** [comment]
Is this deep dish? It also looks like a chain.

**Comment by seafoam6** [comment]
It's not deep dish. Buddy's has 6 locations around the Detroit area. They are the originators of "Detroit Style Pizza" . Copy-pasta from wikipedia: 

Detroit-style pizza is a style of pizza developed in Detroit, Michigan. It is a square pizza similar to Sicilian-style pizza that has a thick deep-dish crisp crust and toppings such as pepperoni and olives, and is served with the marinara sauce on top.[1][2] The square shaped pizza is the result of being baked in a square pan, which is often not a pizza pan.[3] Rather, industrial parts trays are often used, which were originally made to hold small parts in factories.[3]

The crust of a Detroit-style pizza is noteworthy because in addition to occasionally being twice-baked, it is usually baked in a well-oiled pan to a chewy medium-well-done state that gives the bottom and edges of the crust a fried/crunchy texture. Some parlors will apply melted butter with a soft brush prior to baking. The resulting pizza has a warm, chewy texture that, when combined with the sauce and toppings, is intensely flavorful.[4]

**Comment by stevekinney** [comment]
@mikedao I'm totally okay with Sicilian-style pizza.

**Comment by gschorkopf** [comment]
@seafoam6 mind rebasing?

**Comment by seafoam6** [comment]
Yay! I believe I rebased it! learning is fun (but not as fun as pizza).

**Comment by gschorkopf** [comment]
@seafoam6 looks like you did! It's basically ready to merge.

One thing for cleanliness. Have you heard of [squashing](http://makandracards.com/makandra/527-squash-several-git-commits-into-a-single-commit) commits? I think this PR could benefit from squashing your 8 commits into just one. Thoughts?

**Comment by seafoam6** [comment]
Will try some squishing in a bit.

**Comment by stevekinney** [comment]
This still needs rebasing and has a bunch of merge conflicts with the current master branch. Feel free to reopen a new pull request, though!

**Pull request closed without merging**
