### PR TITLE
austin additions

### PR DESCRIPTION
**Pull request by aaronhuckabee**
PS is the intent to actually avoid deep dish places? I haven't included any but am curious.

### CODE REVIEW

**Comment by stevekinney** [comment]
The intent is to include pizza. Deep dish pizza is a form of casserole and is thereby not eligible.

**Comment by aaronhuckabee** [comment]
Savage.

**Comment by aaronhuckabee** [comment]
Savage

**Comment by mikedao** [comment]
Yes, people that enjoy casseroles are indeed savages.

**Pull request merged**
