### PR TITLE
Restructure list - make country 2nd level head.

### PR DESCRIPTION
**Pull request by thyrlian**

### CODE REVIEW

**Comment by mikedao** [comment]
I dunno, America should totally come first.  :us:

**Comment by helen** [comment]
I could see the argument for Italy first, but ya AMERICA.

**Comment by thyrlian** [comment]
IMHO, it should be neutral just like the country / language list which you could find in lots of registration / settings forms.  And there most of the time it sorts United States as it is, starting with letter U, you could easily get it by typing the letters.

According to [wikipedia's countries list](https://en.wikipedia.org/wiki/List_of_countries_and_dependencies_and_their_capitals_in_native_languages) and [country names and ISO codes](https://en.wikipedia.org/?title=ISO_3166-1), which does the same, put USA under the letter U.

From the user's perspective, it's still easy for them to find United States out, since it's well indexed.

Thanks.

**Comment by helen** [comment]
I'm being a little silly, sorry about that :) I do wonder if it perhaps makes sense to go something like:

# Continent

## Country

### State / Province (if applicable)

#### City

**Comment by thyrlian** [comment]
I actually think your hierarchy makes sense.  Since normalization would provide convenience for others to consume it (e.g. maybe later someone would like to scrape it to display Google / Foursquare ratings of each restaurant).

**Comment by stevekinney** [comment]
This is now pretty out of date, so I'm going to close it. :octopus:

**Pull request closed without merging**
