### PR TITLE
Adds address information to each restaurant and maps it

### PR DESCRIPTION
**Pull request by ughitsaaron**
Per #62 adds address information to each restaurant to use for getting coordinates. Guidelines for adding addresses has been added to contribution guidelines.

@cluhring's script was modified to look for address information. [Redcarpet](/vmg/redcarpet) was added for compiling Markdown to HTML for parsing.

Adds a Gemfile for installing dependencies.

### CODE REVIEW

**Comment by cluhring** [comment]
Nice job Aaron aka @aptkf!  How long did it take you to get all those addresses :)
Good thinking using Redcarpet too, I wish I'd thought to use that. 
w00t!

**Comment by ughitsaaron** [comment]
@cluhring Not too long, actually!

**Comment by MappingKat** [comment]
Dang, you all have been busy.  Let me look at the data and see how we can get it on a snazy map.  We could use leaflet.js or mapbox.js-- whichever you all prefer.

**Comment by ughitsaaron** [comment]
@MappingKat either of those would be great! Whatever you're happy with. I'd be happy to help with front-end implementation, etc., as needed, too.

**Comment by edatrix** [comment]
i'd like to request :pizza: markers.  i mean, if you're going to jazz it up, let's jazz it up... ;)

**Comment by mikedao** [comment]
+1 for :pizza: markers.

**Pull request merged**
