### PR TITLE
Add a few spots

### PR DESCRIPTION
**Pull request by techdubb**

### CODE REVIEW

**Comment by mikedao** [comment]
https://github.com/stevekinney/pizza/blob/master/CONTRIBUTING

`Deep dish pizza is not pizza and has no place in this project.`

**Comment by stevekinney** [comment]
Tony's and Jules look legit.

**Comment by techdubb** [comment]
To be honest I couldn't tell if the deep dish bit was a joke or not. Especially since you have Zachary's down for Oakland which specializes in deep dish.

Though Capo's is "Chicago style", they're a sibling restaurant to Tony's and serve other types of great pizza.

If any restaurant that serves deep dish is out, you might be missing out on awesome regular pizza.

**Comment by stevekinney** [comment]
@h0ke I'm inclined to agree with you. I just spelled out my one and only issue in #17 and I'm interested in your opinion.

**Pull request closed without merging**
